#!/bin/sh
remtstm_abis  tstm2_6 8006 create ho1_pool18_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm2_6 8006 create no_ho_pool18_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_6 8006 create moc_ms_18 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 1521 80
remtstm_abis  tstm2_6 8006 create mtc_18 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 7121 80
remtstm_abis  tstm2_6 8006 create moc_fix_18 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 11961 40
remtstm_abis  tstm2_6 8006 create lu_18 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14761 40
remtstm_abis  tstm2_6 8006 create mtsms_18 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 17941 60
remtstm_abis  tstm2_6 8006 create moc_sms_18 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22141 60
exit
