#!/bin/sh
remtstm_abis  tstm3_3 8011 create ho1_pool31_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_3 8011 create no_ho_pool31_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_3 8011 create moc_ms_31 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2561 80
remtstm_abis  tstm3_3 8011 create mtc_31 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8161 80
remtstm_abis  tstm3_3 8011 create moc_fix_31 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12481 40
remtstm_abis  tstm3_3 8011 create lu_31 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15281 40
remtstm_abis  tstm3_3 8011 create mtsms_31 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18721 60
remtstm_abis  tstm3_3 8011 create moc_sms_31 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22921 60
exit
