#!/bin/sh
remtstm_abis  tstm3_3 8011 create ho1_pool33_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_3 8011 create no_ho_pool33_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_3 8011 create moc_ms_33 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2721 80
remtstm_abis  tstm3_3 8011 create mtc_33 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8321 80
remtstm_abis  tstm3_3 8011 create moc_fix_33 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12561 40
remtstm_abis  tstm3_3 8011 create lu_33 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15361 40
remtstm_abis  tstm3_3 8011 create mtsms_33 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18841 60
remtstm_abis  tstm3_3 8011 create moc_sms_33 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 23041 60
exit
