#!/bin/sh
remtstm_abis  tstm3_4 8012 create ho1_pool34_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_4 8012 create no_ho_pool34_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_4 8012 create moc_ms_34 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2801 80
remtstm_abis  tstm3_4 8012 create mtc_34 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8401 80
remtstm_abis  tstm3_4 8012 create moc_fix_34 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12601 40
remtstm_abis  tstm3_4 8012 create lu_34 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15401 40
remtstm_abis  tstm3_4 8012 create mtsms_34 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18901 60
remtstm_abis  tstm3_4 8012 create moc_sms_34 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 23101 60
exit
