#!/bin/sh
remtstm_abis  tstm2_5 8005 create ho1_pool13_bsic2_ncell10 mobprof_pool.tsm 10 9000 2 0 1
remtstm_abis  tstm2_5 8005 create no_ho_pool13_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_5 8005 create moc_ms_13 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 1121 80
remtstm_abis  tstm2_5 8005 create mtc_13 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 6721 80
remtstm_abis  tstm2_5 8005 create moc_fix_13 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 11761 40
remtstm_abis  tstm2_5 8005 create lu_13 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14561 40
remtstm_abis  tstm2_5 8005 create mtsms_13 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 17641 60
remtstm_abis  tstm2_5 8005 create moc_sms_13 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 21841 60
exit
