#!/bin/sh
remtstm_abis  tstm2_7 8007 create ho1_pool20_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm2_7 8007 create no_ho_pool20_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_7 8007 create moc_ms_20 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 1681 80
remtstm_abis  tstm2_7 8007 create mtc_20 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 7281 80
remtstm_abis  tstm2_7 8007 create moc_fix_20 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12041 40
remtstm_abis  tstm2_7 8007 create lu_20 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14841 40
remtstm_abis  tstm2_7 8007 create mtsms_20 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18061 60
remtstm_abis  tstm2_7 8007 create moc_sms_20 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22261 60
exit
