#!/bin/sh
remtstm_abis  tstm2_8 8008 create ho1_pool22_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm2_8 8008 create no_ho_pool22_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_8 8008 create moc_ms_22 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 1841 80
remtstm_abis  tstm2_8 8008 create mtc_22 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 7441 80
remtstm_abis  tstm2_8 8008 create moc_fix_22 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12121 40
remtstm_abis  tstm2_8 8008 create lu_22 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14921 40
remtstm_abis  tstm2_8 8008 create mtsms_22 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18181 60
remtstm_abis  tstm2_8 8008 create moc_sms_22 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22381 60
exit
