#!/bin/sh
remtstm_abis  tstm3_3 8011 create ho1_pool43_bsic4_ncell10 mobprof_pool.tsm 10 9000 4 0 1
remtstm_abis  tstm3_3 8011 create no_ho_pool43_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_3 8011 create moc_ms_43 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 4161 240
remtstm_abis  tstm3_3 8011 create mtc_43 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 9761 240
remtstm_abis  tstm3_3 8011 create moc_fix_43 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 13281 120
remtstm_abis  tstm3_3 8011 create lu_43 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 16081 120
remtstm_abis  tstm3_3 8011 create mtsms_43 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 19921 180
remtstm_abis  tstm3_3 8011 create moc_sms_43 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 24121 180
exit
