#!/bin/sh
remtstm_abis  tstm3_1 8009 create ho1_pool27_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_1 8009 create no_ho_pool27_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_1 8009 create moc_ms_27 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2241 80
remtstm_abis  tstm3_1 8009 create mtc_27 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 7841 80
remtstm_abis  tstm3_1 8009 create moc_fix_27 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12321 40
remtstm_abis  tstm3_1 8009 create lu_27 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15121 40
remtstm_abis  tstm3_1 8009 create mtsms_27 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18481 60
remtstm_abis  tstm3_1 8009 create moc_sms_27 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22681 60
exit
