#!/bin/sh
remtstm_abis  tstm3_1 8009 create ho1_pool26_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_1 8009 create no_ho_pool26_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_1 8009 create moc_ms_26 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2161 80
remtstm_abis  tstm3_1 8009 create mtc_26 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 7761 80
remtstm_abis  tstm3_1 8009 create moc_fix_26 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12281 40
remtstm_abis  tstm3_1 8009 create lu_26 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15081 40
remtstm_abis  tstm3_1 8009 create mtsms_26 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18421 60
remtstm_abis  tstm3_1 8009 create moc_sms_26 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22621 60
exit
