#!/bin/sh
remtstm_abis  tstm2_2 8002 create ho1_pool8_bsic1_ncell10 mobprof_pool.tsm 10 9000 1 0 1
remtstm_abis  tstm2_2 8002 create no_ho_pool8_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_2 8002 create moc_ms_08 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 721 80
remtstm_abis  tstm2_2 8002 create mtc_08 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 6321 80
remtstm_abis  tstm2_2 8002 create moc_fix_08 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 11561 40
remtstm_abis  tstm2_2 8002 create lu_08 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14361 40
remtstm_abis  tstm2_2 8002 create mtsms_08 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 17341 60
remtstm_abis  tstm2_2 8002 create moc_sms_08 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 21541 60
exit
