#!/bin/sh
remtstm_abis  tstm3_5 8013 create ho1_pool38_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_5 8013 create no_ho_pool38_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_5 8013 create moc_ms_38 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 3121 80
remtstm_abis  tstm3_5 8013 create mtc_38 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8721 80
remtstm_abis  tstm3_5 8013 create moc_fix_38 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12761 40
remtstm_abis  tstm3_5 8013 create lu_38 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15561 40
remtstm_abis  tstm3_5 8013 create mtsms_38 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 19141 60
remtstm_abis  tstm3_5 8013 create moc_sms_38 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 23341 60
exit
