#!/bin/sh
remtstm_abis  tstm3_4 8012 create ho1_pool35_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_4 8012 create no_ho_pool35_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_4 8012 create moc_ms_35 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2881 80
remtstm_abis  tstm3_4 8012 create mtc_35 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8481 80
remtstm_abis  tstm3_4 8012 create moc_fix_35 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12641 40
remtstm_abis  tstm3_4 8012 create lu_35 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15441 40
remtstm_abis  tstm3_4 8012 create mtsms_35 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18961 60
remtstm_abis  tstm3_4 8012 create moc_sms_35 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 23161 60
exit
