#!/bin/sh
remtstm_abis  tstm2_2 8002 create ho1_pool2_bsic0_ncell20 mobprof_pool.tsm 20 9000 0 0 1
remtstm_abis  tstm2_2 8002 create no_ho_pool2_ncell20 mobprof_pool.tsm 20 0 0 0 0
remtstm_abis  tstm2_2 8002 create moc_ms_02 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 145 160
remtstm_abis  tstm2_2 8002 create mtc_02 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 5745 160
remtstm_abis  tstm2_2 8002 create moc_fix_02 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 11273 80
remtstm_abis  tstm2_2 8002 create lu_02 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14073 80
remtstm_abis  tstm2_2 8002 create mtsms_02 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 16909 120
remtstm_abis  tstm2_2 8002 create moc_sms_02 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 21109 120
exit
