#!/bin/sh
remtstm_abis  tstm3_2 8010 create ho1_pool29_bsic3_ncell10 mobprof_pool.tsm 10 9000 3 0 1
remtstm_abis  tstm3_2 8010 create no_ho_pool29_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_2 8010 create moc_ms_29 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 2401 80
remtstm_abis  tstm3_2 8010 create mtc_29 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 8001 80
remtstm_abis  tstm3_2 8010 create moc_fix_29 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 12401 40
remtstm_abis  tstm3_2 8010 create lu_29 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 15201 40
remtstm_abis  tstm3_2 8010 create mtsms_29 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 18601 60
remtstm_abis  tstm3_2 8010 create moc_sms_29 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 22801 60
exit
