#!/bin/sh
remtstm_abis  tstm3_8 8016 create ho1_pool48_bsic4_ncell10 mobprof_pool.tsm 10 9000 4 0 1
remtstm_abis  tstm3_8 8016 create no_ho_pool48_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm3_8 8016 create moc_ms_48 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 5361 240
remtstm_abis  tstm3_8 8016 create mtc_48 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 10961 240
remtstm_abis  tstm3_8 8016 create moc_fix_48 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 13881 120
remtstm_abis  tstm3_8 8016 create lu_48 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 16681 120
remtstm_abis  tstm3_8 8016 create mtsms_48 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 20821 180
remtstm_abis  tstm3_8 8016 create moc_sms_48 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 25021 180
exit
