#!/bin/sh
remtstm_abis  tstm2_4 8004 create ho1_pool11_bsic1_ncell10 mobprof_pool.tsm 10 9000 1 0 1
remtstm_abis  tstm2_4 8004 create no_ho_pool11_ncell10 mobprof_pool.tsm 10 0 0 0 0
remtstm_abis  tstm2_4 8004 create moc_ms_11 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 961 80
remtstm_abis  tstm2_4 8004 create mtc_11 ms_mtc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 6561 80
remtstm_abis  tstm2_4 8004 create moc_fix_11 ms_moc.tsm Nom4500_ETH_Abis_MsDb_Mx10A 11681 40
remtstm_abis  tstm2_4 8004 create lu_11 ms_lu.tsm Nom4500_ETH_Abis_MsDb_Mx10A 14481 40
remtstm_abis  tstm2_4 8004 create mtsms_11 ms_mtsms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 17521 60
remtstm_abis  tstm2_4 8004 create moc_sms_11 ms_mosms.tsm Nom4500_ETH_Abis_MsDb_Mx10A 21721 60
exit
