#!/bin/sh
remtstm_abis tstm3_1 8009 status moc_ms_27
remtstm_abis tstm3_1 8009 status mtc_27
remtstm_abis tstm3_1 8009 status moc_fix_27
remtstm_abis tstm3_1 8009 status lu_27
remtstm_abis tstm3_1 8009 status mtsms_27
remtstm_abis tstm3_1 8009 status moc_sms_27
exit
