#!/bin/sh
remtstm_abis tstm3_6 8014 status moc_ms_42
remtstm_abis tstm3_6 8014 status mtc_42
remtstm_abis tstm3_6 8014 status moc_fix_42
remtstm_abis tstm3_6 8014 status lu_42
remtstm_abis tstm3_6 8014 status mtsms_42
remtstm_abis tstm3_6 8014 status moc_sms_42
exit
