#!/bin/sh
remtstm_abis tstm3_2 8010 status moc_ms_29
remtstm_abis tstm3_2 8010 status mtc_29
remtstm_abis tstm3_2 8010 status moc_fix_29
remtstm_abis tstm3_2 8010 status lu_29
remtstm_abis tstm3_2 8010 status mtsms_29
remtstm_abis tstm3_2 8010 status moc_sms_29
exit
