#!/bin/sh
remtstm_abis tstm2_5 8005 status moc_ms_13
remtstm_abis tstm2_5 8005 status mtc_13
remtstm_abis tstm2_5 8005 status moc_fix_13
remtstm_abis tstm2_5 8005 status lu_13
remtstm_abis tstm2_5 8005 status mtsms_13
remtstm_abis tstm2_5 8005 status moc_sms_13
exit
