#!/bin/sh
remtstm_abis tstm3_3 8011 status moc_ms_33
remtstm_abis tstm3_3 8011 status mtc_33
remtstm_abis tstm3_3 8011 status moc_fix_33
remtstm_abis tstm3_3 8011 status lu_33
remtstm_abis tstm3_3 8011 status mtsms_33
remtstm_abis tstm3_3 8011 status moc_sms_33
exit
