#!/bin/sh
remtstm_abis tstm2_1 8001 status moc_ms_03
remtstm_abis tstm2_1 8001 status mtc_03
remtstm_abis tstm2_1 8001 status moc_fix_03
remtstm_abis tstm2_1 8001 status lu_03
remtstm_abis tstm2_1 8001 status mtsms_03
remtstm_abis tstm2_1 8001 status moc_sms_03
exit
