@ECHO OFF
DEL "%systemroot%\Blue Lace 16.bmp"
DEL "%systemroot%\Coffee Bean.bmp"
DEL "%systemroot%\FeatherTexture.bmp"
DEL "%systemroot%\Gone Fishing.bmp"
DEL "%systemroot%\Greenstone.bmp"
DEL "%systemroot%\Prairie Wind.bmp"
DEL "%systemroot%\Rhododendron.bmp"
DEL "%systemroot%\River Sumida.bmp"
DEL "%systemroot%\Santa Fe Stucco.bmp"
DEL "%systemroot%\Soap Bubbles.bmp"
DEL "%systemroot%\Zapotec.bmp"
DEL "%systemroot%\Web\Wallpaper\Crystal.jpg"
DEL "%systemroot%\Web\Wallpaper\Friend.jpg"
DEL "%systemroot%\Web\Wallpaper\Home.jpg"
DEL "%systemroot%\Web\Wallpaper\Moon flower.jpg"
DEL "%systemroot%\Web\Wallpaper\Peace.jpg"
DEL "%systemroot%\Web\Wallpaper\Power.jpg"
DEL "%systemroot%\Web\Wallpaper\Purple flower.jpg"
DEL "%systemroot%\Web\Wallpaper\Radiance.jpg"
DEL "%systemroot%\Web\Wallpaper\Ripple.jpg"
DEL "%systemroot%\Web\Wallpaper\Stonehenge.jpg"
DEL "%systemroot%\Web\Wallpaper\Vortec space.jpg"
DEL "%systemroot%\Web\Wallpaper\Ascent.jpg"
DEL "%systemroot%\Web\Wallpaper\Autumn.jpg"
DEL "%systemroot%\Web\Wallpaper\Azul.jpg"
DEL "%systemroot%\Web\Wallpaper\Follow.jpg"
DEL "%systemroot%\Web\Wallpaper\Red moon desert.jpg"
DEL "%systemroot%\Web\Wallpaper\Tulips.jpg"
DEL "%systemroot%\Web\Wallpaper\Wind.jpg"
